// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  type Options as Options2,
  type TDataShape,
  urlSearchParamsBodySerializer,
} from "./client"
import { client } from "./client.gen"
import type {
  GeminiCancelDeepResearchData,
  GeminiCancelDeepResearchErrors,
  GeminiCancelDeepResearchResponses,
  GeminiDeepResearchSyncData,
  GeminiDeepResearchSyncErrors,
  GeminiDeepResearchSyncResponses,
  GeminiPollDeepResearchData,
  GeminiPollDeepResearchErrors,
  GeminiPollDeepResearchResponses,
  GeminiStartDeepResearchData,
  GeminiStartDeepResearchErrors,
  GeminiStartDeepResearchResponses,
  ItemsCreateItemData,
  ItemsCreateItemErrors,
  ItemsCreateItemResponses,
  ItemsDeleteItemData,
  ItemsDeleteItemErrors,
  ItemsDeleteItemResponses,
  ItemsReadItemData,
  ItemsReadItemErrors,
  ItemsReadItemResponses,
  ItemsReadItemsData,
  ItemsReadItemsErrors,
  ItemsReadItemsResponses,
  ItemsUpdateItemData,
  ItemsUpdateItemErrors,
  ItemsUpdateItemResponses,
  LoginLoginAccessTokenData,
  LoginLoginAccessTokenErrors,
  LoginLoginAccessTokenResponses,
  LoginRecoverPasswordData,
  LoginRecoverPasswordErrors,
  LoginRecoverPasswordHtmlContentData,
  LoginRecoverPasswordHtmlContentErrors,
  LoginRecoverPasswordHtmlContentResponses,
  LoginRecoverPasswordResponses,
  LoginResetPasswordData,
  LoginResetPasswordErrors,
  LoginResetPasswordResponses,
  LoginTestTokenData,
  LoginTestTokenResponses,
  PerplexityDeepResearchData,
  PerplexityDeepResearchErrors,
  PerplexityDeepResearchResponses,
  PrivateCreateUserData,
  PrivateCreateUserErrors,
  PrivateCreateUserResponses,
  TavilyCrawlData,
  TavilyCrawlErrors,
  TavilyCrawlResponses,
  TavilyExtractData,
  TavilyExtractErrors,
  TavilyExtractResponses,
  TavilyMapUrlsData,
  TavilyMapUrlsErrors,
  TavilyMapUrlsResponses,
  TavilySearchData,
  TavilySearchErrors,
  TavilySearchResponses,
  UsersCreateUserData,
  UsersCreateUserErrors,
  UsersCreateUserResponses,
  UsersDeleteUserData,
  UsersDeleteUserErrors,
  UsersDeleteUserMeData,
  UsersDeleteUserMeResponses,
  UsersDeleteUserResponses,
  UsersReadUserByIdData,
  UsersReadUserByIdErrors,
  UsersReadUserByIdResponses,
  UsersReadUserMeData,
  UsersReadUserMeResponses,
  UsersReadUsersData,
  UsersReadUsersErrors,
  UsersReadUsersResponses,
  UsersRegisterUserData,
  UsersRegisterUserErrors,
  UsersRegisterUserResponses,
  UsersUpdatePasswordMeData,
  UsersUpdatePasswordMeErrors,
  UsersUpdatePasswordMeResponses,
  UsersUpdateUserData,
  UsersUpdateUserErrors,
  UsersUpdateUserMeData,
  UsersUpdateUserMeErrors,
  UsersUpdateUserMeResponses,
  UsersUpdateUserResponses,
  UtilsHealthCheckData,
  UtilsHealthCheckResponses,
  UtilsTestEmailData,
  UtilsTestEmailErrors,
  UtilsTestEmailResponses,
} from "./types.gen"

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>
}

/**
 * Login Access Token
 *
 * OAuth2 compatible token login, get an access token for future requests
 */
export const loginLoginAccessToken = <ThrowOnError extends boolean = false>(
  options: Options<LoginLoginAccessTokenData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    LoginLoginAccessTokenResponses,
    LoginLoginAccessTokenErrors,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    responseType: "json",
    url: "/api/v1/login/access-token",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  })

/**
 * Test Token
 *
 * Test access token
 */
export const loginTestToken = <ThrowOnError extends boolean = false>(
  options?: Options<LoginTestTokenData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    LoginTestTokenResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/login/test-token",
    ...options,
  })

/**
 * Recover Password
 *
 * Password Recovery
 */
export const loginRecoverPassword = <ThrowOnError extends boolean = false>(
  options: Options<LoginRecoverPasswordData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    LoginRecoverPasswordResponses,
    LoginRecoverPasswordErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/v1/password-recovery/{email}",
    ...options,
  })

/**
 * Reset Password
 *
 * Reset password
 */
export const loginResetPassword = <ThrowOnError extends boolean = false>(
  options: Options<LoginResetPasswordData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    LoginResetPasswordResponses,
    LoginResetPasswordErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/v1/reset-password/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Recover Password Html Content
 *
 * HTML Content for Password Recovery
 */
export const loginRecoverPasswordHtmlContent = <
  ThrowOnError extends boolean = false,
>(
  options: Options<LoginRecoverPasswordHtmlContentData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    LoginRecoverPasswordHtmlContentResponses,
    LoginRecoverPasswordHtmlContentErrors,
    ThrowOnError
  >({
    responseType: "text",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/password-recovery-html-content/{email}",
    ...options,
  })

/**
 * Read Users
 *
 * Retrieve users.
 */
export const usersReadUsers = <ThrowOnError extends boolean = false>(
  options?: Options<UsersReadUsersData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    UsersReadUsersResponses,
    UsersReadUsersErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/users/",
    ...options,
  })

/**
 * Create User
 *
 * Create new user.
 */
export const usersCreateUser = <ThrowOnError extends boolean = false>(
  options: Options<UsersCreateUserData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    UsersCreateUserResponses,
    UsersCreateUserErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/users/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Delete User Me
 *
 * Delete own user.
 */
export const usersDeleteUserMe = <ThrowOnError extends boolean = false>(
  options?: Options<UsersDeleteUserMeData, ThrowOnError>,
) =>
  (options?.client ?? client).delete<
    UsersDeleteUserMeResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/users/me",
    ...options,
  })

/**
 * Read User Me
 *
 * Get current user.
 */
export const usersReadUserMe = <ThrowOnError extends boolean = false>(
  options?: Options<UsersReadUserMeData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    UsersReadUserMeResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/users/me",
    ...options,
  })

/**
 * Update User Me
 *
 * Update own user.
 */
export const usersUpdateUserMe = <ThrowOnError extends boolean = false>(
  options: Options<UsersUpdateUserMeData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    UsersUpdateUserMeResponses,
    UsersUpdateUserMeErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/users/me",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Update Password Me
 *
 * Update own password.
 */
export const usersUpdatePasswordMe = <ThrowOnError extends boolean = false>(
  options: Options<UsersUpdatePasswordMeData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    UsersUpdatePasswordMeResponses,
    UsersUpdatePasswordMeErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/users/me/password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Register User
 *
 * Create new user without the need to be logged in.
 */
export const usersRegisterUser = <ThrowOnError extends boolean = false>(
  options: Options<UsersRegisterUserData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    UsersRegisterUserResponses,
    UsersRegisterUserErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/v1/users/signup",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Delete User
 *
 * Delete a user.
 */
export const usersDeleteUser = <ThrowOnError extends boolean = false>(
  options: Options<UsersDeleteUserData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    UsersDeleteUserResponses,
    UsersDeleteUserErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/users/{user_id}",
    ...options,
  })

/**
 * Read User By Id
 *
 * Get a specific user by id.
 */
export const usersReadUserById = <ThrowOnError extends boolean = false>(
  options: Options<UsersReadUserByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    UsersReadUserByIdResponses,
    UsersReadUserByIdErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/users/{user_id}",
    ...options,
  })

/**
 * Update User
 *
 * Update a user.
 */
export const usersUpdateUser = <ThrowOnError extends boolean = false>(
  options: Options<UsersUpdateUserData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    UsersUpdateUserResponses,
    UsersUpdateUserErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/users/{user_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Test Email
 *
 * Test emails.
 */
export const utilsTestEmail = <ThrowOnError extends boolean = false>(
  options: Options<UtilsTestEmailData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    UtilsTestEmailResponses,
    UtilsTestEmailErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/utils/test-email/",
    ...options,
  })

/**
 * Health Check
 */
export const utilsHealthCheck = <ThrowOnError extends boolean = false>(
  options?: Options<UtilsHealthCheckData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    UtilsHealthCheckResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/v1/utils/health-check/",
    ...options,
  })

/**
 * Read Items
 *
 * Retrieve items with optional content_type filter.
 */
export const itemsReadItems = <ThrowOnError extends boolean = false>(
  options?: Options<ItemsReadItemsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ItemsReadItemsResponses,
    ItemsReadItemsErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/items/",
    ...options,
  })

/**
 * Create Item
 *
 * Create new item.
 */
export const itemsCreateItem = <ThrowOnError extends boolean = false>(
  options: Options<ItemsCreateItemData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ItemsCreateItemResponses,
    ItemsCreateItemErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/items/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Delete Item
 *
 * Delete an item.
 */
export const itemsDeleteItem = <ThrowOnError extends boolean = false>(
  options: Options<ItemsDeleteItemData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    ItemsDeleteItemResponses,
    ItemsDeleteItemErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/items/{id}",
    ...options,
  })

/**
 * Read Item
 *
 * Get item by ID.
 */
export const itemsReadItem = <ThrowOnError extends boolean = false>(
  options: Options<ItemsReadItemData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    ItemsReadItemResponses,
    ItemsReadItemErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/items/{id}",
    ...options,
  })

/**
 * Update Item
 *
 * Update an item.
 */
export const itemsUpdateItem = <ThrowOnError extends boolean = false>(
  options: Options<ItemsUpdateItemData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    ItemsUpdateItemResponses,
    ItemsUpdateItemErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/items/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Search
 *
 * Perform a web search using Tavily API.
 *
 * Executes a web search with the provided query and parameters, returning
 * relevant search results and optionally an AI-generated answer.
 *
 * Args:
 * current_user: Authenticated user (required for authorization).
 * tavily: Injected TavilyService instance.
 * request: Search request with query and optional parameters.
 *
 * Returns:
 * SearchResponse with query, results, and optional answer/images.
 *
 * Raises:
 * TavilyAPIError: If the Tavily API request fails.
 */
export const tavilySearch = <ThrowOnError extends boolean = false>(
  options: Options<TavilySearchData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    TavilySearchResponses,
    TavilySearchErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/tavily/search",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Extract
 *
 * Extract content from one or more URLs.
 *
 * Uses Tavily extraction API to retrieve clean, structured content from
 * web pages. Supports both single URL and batch URL extraction.
 *
 * Args:
 * current_user: Authenticated user (required for authorization).
 * tavily: Injected TavilyService instance.
 * request: Extract request with URL or list of URLs.
 *
 * Returns:
 * ExtractResponse with extraction results for each URL.
 *
 * Raises:
 * TavilyAPIError: If the Tavily API request fails.
 */
export const tavilyExtract = <ThrowOnError extends boolean = false>(
  options: Options<TavilyExtractData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    TavilyExtractResponses,
    TavilyExtractErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/tavily/extract",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Crawl
 *
 * Crawl a website starting from a given URL.
 *
 * Performs recursive crawling of a website, extracting content from
 * discovered pages up to the specified depth and breadth limits.
 *
 * Args:
 * current_user: Authenticated user (required for authorization).
 * tavily: Injected TavilyService instance.
 * request: Crawl request with URL and crawl parameters.
 *
 * Returns:
 * CrawlResponse with base URL, crawled page results, and total count.
 *
 * Raises:
 * TavilyAPIError: If the Tavily API request fails.
 */
export const tavilyCrawl = <ThrowOnError extends boolean = false>(
  options: Options<TavilyCrawlData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    TavilyCrawlResponses,
    TavilyCrawlErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/tavily/crawl",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Map Urls
 *
 * Generate a sitemap of URLs from a website.
 *
 * Discovers and returns URLs from a website without extracting content.
 * Useful for understanding site structure before targeted extraction.
 *
 * Args:
 * current_user: Authenticated user (required for authorization).
 * tavily: Injected TavilyService instance.
 * request: Map request with URL and mapping parameters.
 *
 * Returns:
 * MapResponse with base URL, discovered URLs, and total count.
 *
 * Raises:
 * TavilyAPIError: If the Tavily API request fails.
 */
export const tavilyMapUrls = <ThrowOnError extends boolean = false>(
  options: Options<TavilyMapUrlsData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    TavilyMapUrlsResponses,
    TavilyMapUrlsErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/tavily/map",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Deep Research
 *
 * Execute a deep research query using Perplexity Sonar API.
 *
 * Performs a deep research query with the provided parameters, returning
 * a comprehensive response with citations and search results.
 *
 * Args:
 * _current_user: Authenticated user (required for authorization).
 * perplexity: Injected PerplexityService instance.
 * request: Deep research request with query and optional parameters.
 *
 * Returns:
 * PerplexityDeepResearchResponse with model response and citations.
 *
 * Raises:
 * PerplexityAPIError: If the Perplexity API request fails.
 */
export const perplexityDeepResearch = <ThrowOnError extends boolean = false>(
  options: Options<PerplexityDeepResearchData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PerplexityDeepResearchResponses,
    PerplexityDeepResearchErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/perplexity/deep-research",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Deep Research Sync
 *
 * Execute a deep research query and wait for completion.
 *
 * Starts a deep research job and blocks until the job reaches a terminal
 * state (completed, failed, or cancelled). This is a convenience endpoint
 * for clients that prefer a synchronous workflow.
 *
 * Note: This endpoint may take 20-60 minutes to complete for complex queries.
 * Consider using the async workflow (POST + polling) for better control.
 *
 * Args:
 * _current_user: Authenticated user (required for authorization).
 * gemini: Injected GeminiService instance.
 * request: Deep research request with query and optional parameters.
 *
 * Returns:
 * GeminiDeepResearchResultResponse with final status and results.
 *
 * Raises:
 * GeminiAPIError: If the job fails or polling exceeds max attempts.
 */
export const geminiDeepResearchSync = <ThrowOnError extends boolean = false>(
  options: Options<GeminiDeepResearchSyncData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    GeminiDeepResearchSyncResponses,
    GeminiDeepResearchSyncErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/gemini/deep-research/sync",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Start Deep Research
 *
 * Start a new deep research job.
 *
 * Submits a research query to the Gemini API and returns immediately with
 * an interaction ID. Use the poll endpoint to check job status and retrieve
 * results when complete.
 *
 * Args:
 * _current_user: Authenticated user (required for authorization).
 * gemini: Injected GeminiService instance.
 * request: Deep research request with query and optional parameters.
 *
 * Returns:
 * GeminiDeepResearchJobResponse with interaction_id and initial status.
 *
 * Raises:
 * GeminiAPIError: If the API request fails for any reason.
 */
export const geminiStartDeepResearch = <ThrowOnError extends boolean = false>(
  options: Options<GeminiStartDeepResearchData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    GeminiStartDeepResearchResponses,
    GeminiStartDeepResearchErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/gemini/deep-research",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Cancel Deep Research
 *
 * Cancel a running deep research job.
 *
 * Terminates a running research job. Returns successfully if the job was
 * cancelled or was already in a terminal state.
 *
 * Args:
 * _current_user: Authenticated user (required for authorization).
 * gemini: Injected GeminiService instance.
 * interaction_id: The interaction ID of the job to cancel.
 *
 * Returns:
 * Success message confirming cancellation.
 *
 * Raises:
 * GeminiAPIError: If the cancellation request fails.
 */
export const geminiCancelDeepResearch = <ThrowOnError extends boolean = false>(
  options: Options<GeminiCancelDeepResearchData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    GeminiCancelDeepResearchResponses,
    GeminiCancelDeepResearchErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/gemini/deep-research/{interaction_id}",
    ...options,
  })

/**
 * Poll Deep Research
 *
 * Poll for deep research job status and results.
 *
 * Retrieves the current status and any available outputs from a running
 * research job. The last_event_id parameter enables reconnection after
 * network interruption, allowing clients to resume from where they left off.
 *
 * Args:
 * _current_user: Authenticated user (required for authorization).
 * gemini: Injected GeminiService instance.
 * interaction_id: The interaction ID from job creation.
 * last_event_id: Optional ID of last received event for reconnection.
 *
 * Returns:
 * GeminiDeepResearchResultResponse with current status and outputs.
 *
 * Raises:
 * GeminiAPIError: If the interaction is not found or polling fails.
 */
export const geminiPollDeepResearch = <ThrowOnError extends boolean = false>(
  options: Options<GeminiPollDeepResearchData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GeminiPollDeepResearchResponses,
    GeminiPollDeepResearchErrors,
    ThrowOnError
  >({
    responseType: "json",
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/v1/gemini/deep-research/{interaction_id}",
    ...options,
  })

/**
 * Create User
 *
 * Create a new user.
 */
export const privateCreateUser = <ThrowOnError extends boolean = false>(
  options: Options<PrivateCreateUserData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PrivateCreateUserResponses,
    PrivateCreateUserErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/v1/private/users/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })
