// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * Body_login-login_access_token
 */
export type BodyLoginLoginAccessToken = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * CrawlRequest
 *
 * Request schema for Tavily site crawling.
 *
 * Contains parameters for recursive website crawling including depth,
 * breadth, limits, and path/domain filtering options.
 */
export type CrawlRequest = {
    /**
     * Url
     *
     * Starting URL for the crawl
     */
    url: string;
    /**
     * Max Depth
     *
     * Maximum link depth to crawl from starting URL (0 = starting page only)
     */
    max_depth?: number;
    /**
     * Max Breadth
     *
     * Maximum number of links to follow per page
     */
    max_breadth?: number;
    /**
     * Limit
     *
     * Maximum total number of pages to crawl
     */
    limit?: number;
    /**
     * Instructions
     *
     * Natural language instructions for content selection
     */
    instructions?: string | null;
    /**
     * Select Paths
     *
     * URL path patterns to include in crawl (e.g., ['/docs/', '/api/'])
     */
    select_paths?: Array<string> | null;
    /**
     * Select Domains
     *
     * Additional domains to include in crawl (e.g., ['api.example.com'])
     */
    select_domains?: Array<string> | null;
};

/**
 * CrawlResponse
 *
 * Response schema for Tavily site crawling.
 *
 * Contains the base URL, list of crawled page results, and total count.
 */
export type CrawlResponse = {
    /**
     * Base Url
     *
     * The starting URL for the crawl
     */
    base_url: string;
    /**
     * Results
     *
     * List of crawled page results with content
     */
    results?: Array<CrawlResult>;
    /**
     * Total Pages
     *
     * Total number of pages successfully crawled
     */
    total_pages?: number;
    [key: string]: unknown;
};

/**
 * CrawlResult
 *
 * Individual page result from site crawling.
 *
 * Represents a single crawled page with its URL and extracted content.
 */
export type CrawlResult = {
    /**
     * Url
     *
     * URL of the crawled page
     */
    url: string;
    /**
     * Raw Content
     *
     * Extracted text content from the page
     */
    raw_content?: string | null;
    /**
     * Metadata
     *
     * Additional metadata about the crawled page
     */
    metadata?: {
        [key: string]: unknown;
    } | null;
    [key: string]: unknown;
};

/**
 * ExtractRequest
 *
 * Request schema for Tavily URL content extraction.
 *
 * Supports both single URL and batch URL extraction. The urls field
 * accepts either a single URL string or a list of URL strings.
 */
export type ExtractRequest = {
    /**
     * Urls
     *
     * Single URL or list of URLs to extract content from
     */
    urls: string | Array<string>;
};

/**
 * ExtractResponse
 *
 * Response schema for Tavily URL content extraction.
 *
 * Contains the extraction results for all requested URLs.
 */
export type ExtractResponse = {
    /**
     * Results
     *
     * List of extraction results for each URL
     */
    results?: Array<ExtractResult>;
    /**
     * Failed Results
     *
     * List of URLs that failed to extract with error details
     */
    failed_results?: Array<{
        [key: string]: unknown;
    }>;
    [key: string]: unknown;
};

/**
 * ExtractResult
 *
 * Extraction result for a single URL.
 *
 * Contains the extracted content from a URL including text and images.
 */
export type ExtractResult = {
    /**
     * Url
     *
     * Source URL that was extracted
     */
    url: string;
    /**
     * Raw Content
     *
     * Extracted text content from the page
     */
    raw_content: string;
    /**
     * Images
     *
     * List of image URLs found on the page
     */
    images?: Array<string>;
    [key: string]: unknown;
};

/**
 * GeminiDeepResearchJobResponse
 *
 * Response schema for Gemini deep research job creation.
 *
 * Returned immediately after submitting a new deep research request.
 * Contains the interaction ID needed for subsequent polling.
 */
export type GeminiDeepResearchJobResponse = {
    /**
     * Id
     *
     * Unique identifier for this research interaction
     */
    id: string;
    /**
     * Initial status of the job (typically pending)
     */
    status?: GeminiInteractionStatus;
    /**
     * Createtime
     *
     * Timestamp when the job was created
     */
    createTime?: string | null;
    [key: string]: unknown;
};

/**
 * GeminiDeepResearchRequest
 *
 * Request schema for initiating a Gemini deep research job.
 *
 * Contains all parameters for submitting a new deep research query.
 * The job runs asynchronously and returns an interaction ID for polling.
 *
 * Parameter Groups:
 * Core: query (required)
 * Options: enable_thinking_summaries, file_search_store_names
 * Continuation: previous_interaction_id
 */
export type GeminiDeepResearchRequest = {
    /**
     * Query
     *
     * The research query to investigate
     */
    query: string;
    /**
     * Enable Thinking Summaries
     *
     * Include thinking/reasoning summaries in responses
     */
    enable_thinking_summaries?: boolean;
    /**
     * File Search Store Names
     *
     * Names of file stores to search for context
     */
    file_search_store_names?: Array<string> | null;
    /**
     * Previous Interaction Id
     *
     * ID of previous interaction for continuation
     */
    previous_interaction_id?: string | null;
};

/**
 * GeminiDeepResearchResultResponse
 *
 * Response schema for Gemini deep research polling results.
 *
 * Contains the current status and any available results from polling.
 * When status is COMPLETED, outputs and usage will be populated.
 */
export type GeminiDeepResearchResultResponse = {
    /**
     * Current status of the research job
     */
    status: GeminiInteractionStatus;
    /**
     * Outputs
     *
     * List of output segments from the research
     */
    outputs?: Array<GeminiOutput>;
    /**
     * Token usage information (available on completion)
     */
    usage?: GeminiUsage | null;
    /**
     * Completed At
     *
     * Timestamp when the job completed (if applicable)
     */
    completed_at?: string | null;
    /**
     * Event Id
     *
     * ID of this event for reconnection tracking
     */
    event_id?: string | null;
    /**
     * Type of streaming event (if applicable)
     */
    event_type?: GeminiStreamEventType | null;
    /**
     * Error Message
     *
     * Error message if status is FAILED
     */
    error_message?: string | null;
    [key: string]: unknown;
};

/**
 * GeminiDeltaType
 *
 * Delta types for incremental response updates.
 *
 * Categorizes the type of content in incremental streaming updates.
 *
 * Attributes:
 * TEXT: Text content delta.
 * TOOL_CALL: Tool/function call delta.
 * STATUS: Status change delta.
 */
export type GeminiDeltaType = 'text' | 'tool_call' | 'status';

/**
 * GeminiInteractionStatus
 *
 * Status states for Gemini deep research interactions.
 *
 * Represents the lifecycle states of an async deep research job from
 * submission through completion or failure.
 *
 * Attributes:
 * PENDING: Job submitted but not yet started processing.
 * IN_PROGRESS: Job is actively being processed.
 * COMPLETED: Job finished successfully with results available.
 * FAILED: Job encountered an error and could not complete.
 * CANCELLED: Job was cancelled before completion.
 */
export type GeminiInteractionStatus = 'pending' | 'in_progress' | 'completed' | 'failed' | 'cancelled';

/**
 * GeminiOutput
 *
 * Individual output segment from Gemini deep research response.
 *
 * Represents a content segment which may include text, thinking summaries,
 * or tool call results.
 */
export type GeminiOutput = {
    /**
     * Content
     *
     * Text content of this output segment
     */
    content?: string;
    /**
     * Thinking Summary
     *
     * Summary of reasoning/thinking for this segment
     */
    thinking_summary?: string | null;
    /**
     * Type of content in this output (text, tool_call, status)
     */
    delta_type?: GeminiDeltaType;
    [key: string]: unknown;
};

/**
 * GeminiStreamEventType
 *
 * Event types for Gemini streaming responses during polling.
 *
 * Identifies the type of event received when polling for job progress,
 * enabling clients to handle different event types appropriately.
 *
 * Attributes:
 * THINKING_UPDATE: Progress update on reasoning/thinking process.
 * RESEARCH_UPDATE: Progress update on research gathering.
 * FINAL_RESULT: Final result payload with complete response.
 * ERROR: Error event indicating job failure.
 */
export type GeminiStreamEventType = 'thinking_update' | 'research_update' | 'final_result' | 'error';

/**
 * GeminiUsage
 *
 * Token usage information from Gemini API response.
 *
 * Contains token counts for monitoring API usage and costs.
 */
export type GeminiUsage = {
    /**
     * Input Tokens
     *
     * Number of tokens in the input prompt
     */
    input_tokens?: number;
    /**
     * Output Tokens
     *
     * Number of tokens in the generated output
     */
    output_tokens?: number;
    /**
     * Total Tokens
     *
     * Total tokens used in the request
     */
    total_tokens?: number;
    [key: string]: unknown;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ItemCreate
 */
export type ItemCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Source Url
     */
    source_url?: string | null;
    /**
     * Content
     */
    content?: string | null;
    /**
     * Content Type
     */
    content_type?: 'search' | 'extract' | 'crawl' | 'map' | 'perplexity' | 'gemini' | 'youcom' | null;
    /**
     * Item Metadata
     */
    item_metadata?: {
        [key: string]: unknown;
    } | null;
};

/**
 * ItemPublic
 */
export type ItemPublic = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Source Url
     */
    source_url?: string | null;
    /**
     * Content
     */
    content?: string | null;
    /**
     * Content Type
     */
    content_type?: 'search' | 'extract' | 'crawl' | 'map' | 'perplexity' | 'gemini' | 'youcom' | null;
    /**
     * Item Metadata
     */
    item_metadata?: {
        [key: string]: unknown;
    } | null;
    /**
     * Id
     */
    id: string;
    /**
     * Owner Id
     */
    owner_id: string;
};

/**
 * ItemUpdate
 */
export type ItemUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Source Url
     */
    source_url?: string | null;
    /**
     * Content
     */
    content?: string | null;
    /**
     * Content Type
     */
    content_type?: 'search' | 'extract' | 'crawl' | 'map' | 'perplexity' | 'gemini' | 'youcom' | null;
    /**
     * Item Metadata
     */
    item_metadata?: {
        [key: string]: unknown;
    } | null;
};

/**
 * ItemsPublic
 */
export type ItemsPublic = {
    /**
     * Data
     */
    data: Array<ItemPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * MapRequest
 *
 * Request schema for Tavily URL mapping (sitemap generation).
 *
 * Contains parameters for discovering URLs from a website without
 * extracting content. Useful for understanding site structure.
 */
export type MapRequest = {
    /**
     * Url
     *
     * Starting URL for mapping
     */
    url: string;
    /**
     * Max Depth
     *
     * Maximum link depth to discover from starting URL
     */
    max_depth?: number;
    /**
     * Max Breadth
     *
     * Maximum number of links to follow per page
     */
    max_breadth?: number;
    /**
     * Limit
     *
     * Maximum total number of URLs to discover
     */
    limit?: number;
    /**
     * Instructions
     *
     * Natural language instructions for URL selection
     */
    instructions?: string | null;
    /**
     * Select Paths
     *
     * URL path patterns to include (e.g., ['/products/', '/docs/'])
     */
    select_paths?: Array<string> | null;
    /**
     * Select Domains
     *
     * Additional domains to include in mapping
     */
    select_domains?: Array<string> | null;
};

/**
 * MapResponse
 *
 * Response schema for Tavily URL mapping.
 *
 * Contains the base URL, list of discovered URLs, and total count.
 */
export type MapResponse = {
    /**
     * Base Url
     *
     * The starting URL for mapping
     */
    base_url: string;
    /**
     * Urls
     *
     * List of discovered URL strings
     */
    urls?: Array<string>;
    /**
     * Total Urls
     *
     * Total number of URLs discovered
     */
    total_urls?: number;
    [key: string]: unknown;
};

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * NewPassword
 */
export type NewPassword = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * PerplexityChoice
 *
 * Individual choice from Perplexity response.
 *
 * Represents one possible response from the model.
 */
export type PerplexityChoice = {
    /**
     * Index
     *
     * Index of this choice in the list
     */
    index?: number;
    /**
     * The message content for this choice
     */
    message: PerplexityMessage;
    /**
     * Finish Reason
     *
     * Reason the model stopped generating (stop, length, etc.)
     */
    finish_reason?: string | null;
    [key: string]: unknown;
};

/**
 * PerplexityDeepResearchRequest
 *
 * Request schema for Perplexity Sonar deep research queries.
 *
 * Contains all parameters for performing a deep research query including
 * core settings, reasoning options, generation parameters, and search filters.
 *
 * Parameter Groups:
 * Core: query, model, system_prompt
 * Reasoning: search_mode, reasoning_effort, search_context_size
 * Generation: max_tokens, temperature, top_p, top_k, presence_penalty,
 * frequency_penalty
 * Search Filters: search_recency_filter, search_domain_filter,
 * search_after_date_filter, search_before_date_filter
 * Output Options: return_images, return_related_questions
 * Control: stream
 */
export type PerplexityDeepResearchRequest = {
    /**
     * Query
     *
     * The research query to answer
     */
    query: string;
    /**
     * Model
     *
     * Perplexity model to use (sonar-deep-research for exhaustive research)
     */
    model?: string;
    /**
     * System Prompt
     *
     * System prompt to guide the model behavior
     */
    system_prompt?: string | null;
    /**
     * Search mode (auto, news, academic, social)
     */
    search_mode?: PerplexitySearchMode | null;
    /**
     * Reasoning effort level for reasoning models
     */
    reasoning_effort?: PerplexityReasoningEffort | null;
    /**
     * Amount of search context to include
     */
    search_context_size?: PerplexitySearchContextSize | null;
    /**
     * Max Tokens
     *
     * Maximum tokens in the response (1-16384)
     */
    max_tokens?: number | null;
    /**
     * Temperature
     *
     * Sampling temperature (0.0-2.0)
     */
    temperature?: number | null;
    /**
     * Top P
     *
     * Nucleus sampling probability (0.0-1.0)
     */
    top_p?: number | null;
    /**
     * Top K
     *
     * Top-k sampling parameter
     */
    top_k?: number | null;
    /**
     * Presence Penalty
     *
     * Presence penalty (-2.0 to 2.0)
     */
    presence_penalty?: number | null;
    /**
     * Frequency Penalty
     *
     * Frequency penalty (-2.0 to 2.0)
     */
    frequency_penalty?: number | null;
    /**
     * Filter results by recency (hour, day, week, month)
     */
    search_recency_filter?: PerplexityRecencyFilter | null;
    /**
     * Search Domain Filter
     *
     * Domains to include/exclude (prefix with - to exclude)
     */
    search_domain_filter?: Array<string> | null;
    /**
     * Search After Date Filter
     *
     * Only include content after this date (MM/DD/YYYY format)
     */
    search_after_date_filter?: string | null;
    /**
     * Search Before Date Filter
     *
     * Only include content before this date (MM/DD/YYYY format)
     */
    search_before_date_filter?: string | null;
    /**
     * Return Images
     *
     * Include images in the response (Tier-2+ only)
     */
    return_images?: boolean;
    /**
     * Return Related Questions
     *
     * Include related follow-up questions
     */
    return_related_questions?: boolean;
    /**
     * Stream
     *
     * Enable streaming response
     */
    stream?: boolean;
};

/**
 * PerplexityDeepResearchResponse
 *
 * Response schema for Perplexity Sonar deep research queries.
 *
 * Contains the model response with choices, citations, usage information,
 * and optional images and related questions.
 */
export type PerplexityDeepResearchResponse = {
    /**
     * Id
     *
     * Unique identifier for this response
     */
    id: string;
    /**
     * Model
     *
     * Model used for the response
     */
    model: string;
    /**
     * Created
     *
     * Unix timestamp of response creation
     */
    created?: number;
    /**
     * Object
     *
     * Object type (chat.completion)
     */
    object?: string;
    /**
     * Choices
     *
     * List of response choices
     */
    choices?: Array<PerplexityChoice>;
    /**
     * Citations
     *
     * List of citation URLs referenced in the response
     */
    citations?: Array<string>;
    /**
     * Search Results
     *
     * Detailed search results with snippets
     */
    search_results?: Array<PerplexitySearchResult>;
    /**
     * Images
     *
     * Image URLs included in the response
     */
    images?: Array<string>;
    /**
     * Videos
     *
     * Video results included in the response
     */
    videos?: Array<PerplexityVideo>;
    /**
     * Related Questions
     *
     * Related follow-up questions
     */
    related_questions?: Array<string>;
    /**
     * Token usage information
     */
    usage?: PerplexityUsage | null;
    [key: string]: unknown;
};

/**
 * PerplexityMessage
 *
 * Message content from Perplexity response.
 *
 * Contains the role and content of a message in the conversation.
 */
export type PerplexityMessage = {
    /**
     * Role
     *
     * Role of the message author (assistant, user, system)
     */
    role?: string;
    /**
     * Content
     *
     * Text content of the message
     */
    content?: string;
    [key: string]: unknown;
};

/**
 * PerplexityReasoningEffort
 *
 * Reasoning effort levels for Perplexity reasoning models.
 *
 * Controls the depth of reasoning applied to complex queries.
 *
 * Attributes:
 * LOW: Quick responses with minimal reasoning.
 * MEDIUM: Balanced reasoning for general queries.
 * HIGH: Deep reasoning for complex analytical tasks.
 */
export type PerplexityReasoningEffort = 'low' | 'medium' | 'high';

/**
 * PerplexityRecencyFilter
 *
 * Recency filter options for search results.
 *
 * Filters search results to content published within the specified timeframe.
 *
 * Attributes:
 * HOUR: Content from the last hour.
 * DAY: Content from the last 24 hours.
 * WEEK: Content from the last 7 days.
 * MONTH: Content from the last 30 days.
 */
export type PerplexityRecencyFilter = 'hour' | 'day' | 'week' | 'month';

/**
 * PerplexitySearchContextSize
 *
 * Search context size options for Perplexity Sonar API.
 *
 * Controls the amount of search context included in the response.
 *
 * Attributes:
 * LOW: Minimal context for faster responses.
 * MEDIUM: Balanced context size.
 * HIGH: Maximum context for comprehensive answers.
 */
export type PerplexitySearchContextSize = 'low' | 'medium' | 'high';

/**
 * PerplexitySearchMode
 *
 * Search mode options for Perplexity Sonar API.
 *
 * Controls the type of search performed for the query.
 *
 * Attributes:
 * AUTO: Automatic mode selection based on query content.
 * NEWS: Focus on recent news articles and updates.
 * ACADEMIC: Prioritize scholarly sources like peer-reviewed papers.
 * SOCIAL: Include social media and community discussions.
 */
export type PerplexitySearchMode = 'auto' | 'news' | 'academic' | 'social';

/**
 * PerplexitySearchResult
 *
 * Individual search result citation from Perplexity response.
 *
 * Represents a single source citation with URL, title, and content snippet.
 */
export type PerplexitySearchResult = {
    /**
     * Url
     *
     * URL of the source page
     */
    url: string;
    /**
     * Title
     *
     * Title of the source page
     */
    title?: string | null;
    /**
     * Snippet
     *
     * Content snippet from the source
     */
    snippet?: string | null;
    [key: string]: unknown;
};

/**
 * PerplexityUsage
 *
 * Token usage information from Perplexity API response.
 *
 * Contains token counts for monitoring API usage and costs.
 */
export type PerplexityUsage = {
    /**
     * Prompt Tokens
     *
     * Number of tokens in the prompt
     */
    prompt_tokens?: number;
    /**
     * Completion Tokens
     *
     * Number of tokens in the completion
     */
    completion_tokens?: number;
    /**
     * Total Tokens
     *
     * Total tokens used in the request
     */
    total_tokens?: number;
    /**
     * Search Context Size
     *
     * Search context size used for the request
     */
    search_context_size?: string | null;
    [key: string]: unknown;
};

/**
 * PerplexityVideo
 *
 * Video result from Perplexity search.
 *
 * Represents a video found during search with URL and metadata.
 */
export type PerplexityVideo = {
    /**
     * Url
     *
     * URL of the video
     */
    url: string;
    /**
     * Title
     *
     * Title of the video
     */
    title?: string | null;
    /**
     * Thumbnail
     *
     * URL of the video thumbnail
     */
    thumbnail?: string | null;
    [key: string]: unknown;
};

/**
 * PrivateUserCreate
 */
export type PrivateUserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Is Verified
     */
    is_verified?: boolean;
};

/**
 * SearchDepth
 *
 * Search depth options for Tavily web search.
 *
 * Attributes:
 * BASIC: Standard search, faster response time.
 * ADVANCED: Comprehensive search with more detailed results.
 */
export type SearchDepth = 'basic' | 'advanced';

/**
 * SearchImage
 *
 * Image result from Tavily search.
 *
 * Represents an image found during search with URL and optional description.
 */
export type SearchImage = {
    /**
     * Url
     *
     * URL of the image
     */
    url: string;
    /**
     * Description
     *
     * Description of the image (if include_image_descriptions=True)
     */
    description?: string | null;
    [key: string]: unknown;
};

/**
 * SearchRequest
 *
 * Request schema for Tavily web search.
 *
 * Contains all parameters for performing a web search including query,
 * depth settings, result filtering, and content inclusion options.
 */
export type SearchRequest = {
    /**
     * Query
     *
     * Search query string
     */
    query: string;
    /**
     * Search depth - basic for faster results, advanced for comprehensive
     */
    search_depth?: SearchDepth;
    /**
     * Topic category - general for web content, news for recent articles
     */
    topic?: SearchTopic;
    /**
     * Max Results
     *
     * Maximum number of results to return (1-20)
     */
    max_results?: number;
    /**
     * Include Images
     *
     * Include relevant images in search results
     */
    include_images?: boolean;
    /**
     * Include Image Descriptions
     *
     * Include descriptions for images (requires include_images=True)
     */
    include_image_descriptions?: boolean;
    /**
     * Include Answer
     *
     * Include AI-generated answer summary
     */
    include_answer?: boolean;
    /**
     * Include Raw Content
     *
     * Include raw HTML content of result pages
     */
    include_raw_content?: boolean;
    /**
     * Include Domains
     *
     * List of domains to restrict search to (e.g., ['example.com'])
     */
    include_domains?: Array<string> | null;
    /**
     * Exclude Domains
     *
     * List of domains to exclude from search (e.g., ['pinterest.com'])
     */
    exclude_domains?: Array<string> | null;
};

/**
 * SearchResponse
 *
 * Response schema for Tavily web search.
 *
 * Contains the original query, list of search results, and optional
 * AI-generated answer and images based on request parameters.
 */
export type SearchResponse = {
    /**
     * Query
     *
     * The original search query
     */
    query: string;
    /**
     * Results
     *
     * List of search results
     */
    results?: Array<SearchResult>;
    /**
     * Answer
     *
     * AI-generated answer summary (if include_answer=True)
     */
    answer?: string | null;
    /**
     * Images
     *
     * List of relevant images (if include_images=True)
     */
    images?: Array<SearchImage>;
    [key: string]: unknown;
};

/**
 * SearchResult
 *
 * Individual search result from Tavily web search.
 *
 * Represents a single search result with URL, title, content snippet,
 * and optional additional fields based on search parameters.
 */
export type SearchResult = {
    /**
     * Url
     *
     * URL of the search result page
     */
    url: string;
    /**
     * Title
     *
     * Title of the search result page
     */
    title: string;
    /**
     * Content
     *
     * Snippet or summary of the page content
     */
    content: string;
    /**
     * Score
     *
     * Relevance score for this result
     */
    score: number;
    /**
     * Raw Content
     *
     * Raw HTML content of the page (if include_raw_content=True)
     */
    raw_content?: string | null;
    [key: string]: unknown;
};

/**
 * SearchTopic
 *
 * Search topic categories for Tavily web search.
 *
 * Attributes:
 * GENERAL: General web content search.
 * NEWS: News-focused search for recent articles and updates.
 */
export type SearchTopic = 'general' | 'news';

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Id
     */
    id: string;
};

/**
 * UserRegister
 */
export type UserRegister = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name?: string | null;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password?: string | null;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * YouComDeepResearchRequest
 *
 * Request schema for synchronous You.com deep research queries.
 */
export type YouComDeepResearchRequest = {
    /**
     * Query
     *
     * The research query to answer
     */
    query: string;
    /**
     * Depth and cost tier for You.com research
     */
    research_effort?: YouComResearchEffort;
};

/**
 * YouComDeepResearchResponse
 *
 * Response schema for synchronous You.com deep research queries.
 */
export type YouComDeepResearchResponse = {
    /**
     * Main You.com research output
     */
    output: YouComOutput;
    [key: string]: unknown;
};

/**
 * YouComOutput
 *
 * Main You.com research output payload.
 */
export type YouComOutput = {
    /**
     * Content
     *
     * Markdown-formatted research content
     */
    content?: string;
    /**
     * Content Type
     *
     * Format of the content field
     */
    content_type?: string;
    /**
     * Sources
     *
     * Sources cited in the research output
     */
    sources?: Array<YouComSource>;
    [key: string]: unknown;
};

/**
 * YouComResearchEffort
 *
 * Research effort levels for You.com deep research queries.
 */
export type YouComResearchEffort = 'lite' | 'standard' | 'deep' | 'exhaustive';

/**
 * YouComSource
 *
 * Individual source cited by the You.com research response.
 */
export type YouComSource = {
    /**
     * Url
     *
     * URL of the cited source
     */
    url: string;
    /**
     * Title
     *
     * Title of the cited source
     */
    title?: string | null;
    /**
     * Snippets
     *
     * Relevant snippets extracted from the source
     */
    snippets?: Array<string>;
    [key: string]: unknown;
};

export type LoginLoginAccessTokenData = {
    body: BodyLoginLoginAccessToken;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type LoginLoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginLoginAccessTokenError = LoginLoginAccessTokenErrors[keyof LoginLoginAccessTokenErrors];

export type LoginLoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type LoginLoginAccessTokenResponse = LoginLoginAccessTokenResponses[keyof LoginLoginAccessTokenResponses];

export type LoginTestTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type LoginTestTokenResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type LoginTestTokenResponse = LoginTestTokenResponses[keyof LoginTestTokenResponses];

export type LoginRecoverPasswordData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery/{email}';
};

export type LoginRecoverPasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginRecoverPasswordError = LoginRecoverPasswordErrors[keyof LoginRecoverPasswordErrors];

export type LoginRecoverPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type LoginRecoverPasswordResponse = LoginRecoverPasswordResponses[keyof LoginRecoverPasswordResponses];

export type LoginResetPasswordData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/api/v1/reset-password/';
};

export type LoginResetPasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginResetPasswordError = LoginResetPasswordErrors[keyof LoginResetPasswordErrors];

export type LoginResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type LoginResetPasswordResponse = LoginResetPasswordResponses[keyof LoginResetPasswordResponses];

export type LoginRecoverPasswordHtmlContentData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery-html-content/{email}';
};

export type LoginRecoverPasswordHtmlContentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginRecoverPasswordHtmlContentError = LoginRecoverPasswordHtmlContentErrors[keyof LoginRecoverPasswordHtmlContentErrors];

export type LoginRecoverPasswordHtmlContentResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type LoginRecoverPasswordHtmlContentResponse = LoginRecoverPasswordHtmlContentResponses[keyof LoginRecoverPasswordHtmlContentResponses];

export type UsersReadUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users/';
};

export type UsersReadUsersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersReadUsersError = UsersReadUsersErrors[keyof UsersReadUsersErrors];

export type UsersReadUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type UsersReadUsersResponse = UsersReadUsersResponses[keyof UsersReadUsersResponses];

export type UsersCreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type UsersCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersCreateUserError = UsersCreateUserErrors[keyof UsersCreateUserErrors];

export type UsersCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersCreateUserResponse = UsersCreateUserResponses[keyof UsersCreateUserResponses];

export type UsersDeleteUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersDeleteUserMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersDeleteUserMeResponse = UsersDeleteUserMeResponses[keyof UsersDeleteUserMeResponses];

export type UsersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersReadUserMeResponse = UsersReadUserMeResponses[keyof UsersReadUserMeResponses];

export type UsersUpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersUpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdateUserMeError = UsersUpdateUserMeErrors[keyof UsersUpdateUserMeErrors];

export type UsersUpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersUpdateUserMeResponse = UsersUpdateUserMeResponses[keyof UsersUpdateUserMeResponses];

export type UsersUpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type UsersUpdatePasswordMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdatePasswordMeError = UsersUpdatePasswordMeErrors[keyof UsersUpdatePasswordMeErrors];

export type UsersUpdatePasswordMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersUpdatePasswordMeResponse = UsersUpdatePasswordMeResponses[keyof UsersUpdatePasswordMeResponses];

export type UsersRegisterUserData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/users/signup';
};

export type UsersRegisterUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersRegisterUserError = UsersRegisterUserErrors[keyof UsersRegisterUserErrors];

export type UsersRegisterUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersRegisterUserResponse = UsersRegisterUserResponses[keyof UsersRegisterUserResponses];

export type UsersDeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersDeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersDeleteUserError = UsersDeleteUserErrors[keyof UsersDeleteUserErrors];

export type UsersDeleteUserResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersDeleteUserResponse = UsersDeleteUserResponses[keyof UsersDeleteUserResponses];

export type UsersReadUserByIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersReadUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersReadUserByIdError = UsersReadUserByIdErrors[keyof UsersReadUserByIdErrors];

export type UsersReadUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersReadUserByIdResponse = UsersReadUserByIdResponses[keyof UsersReadUserByIdResponses];

export type UsersUpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdateUserError = UsersUpdateUserErrors[keyof UsersUpdateUserErrors];

export type UsersUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersUpdateUserResponse = UsersUpdateUserResponses[keyof UsersUpdateUserResponses];

export type UtilsTestEmailData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email To
         */
        email_to: string;
    };
    url: '/api/v1/utils/test-email/';
};

export type UtilsTestEmailErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UtilsTestEmailError = UtilsTestEmailErrors[keyof UtilsTestEmailErrors];

export type UtilsTestEmailResponses = {
    /**
     * Successful Response
     */
    201: Message;
};

export type UtilsTestEmailResponse = UtilsTestEmailResponses[keyof UtilsTestEmailResponses];

export type UtilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type UtilsHealthCheckResponses = {
    /**
     * Response Utils-Health Check
     *
     * Successful Response
     */
    200: boolean;
};

export type UtilsHealthCheckResponse = UtilsHealthCheckResponses[keyof UtilsHealthCheckResponses];

export type ItemsReadItemsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Content Type
         */
        content_type?: 'search' | 'extract' | 'crawl' | 'map' | 'perplexity' | 'gemini' | 'youcom' | null;
    };
    url: '/api/v1/items/';
};

export type ItemsReadItemsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ItemsReadItemsError = ItemsReadItemsErrors[keyof ItemsReadItemsErrors];

export type ItemsReadItemsResponses = {
    /**
     * Successful Response
     */
    200: ItemsPublic;
};

export type ItemsReadItemsResponse = ItemsReadItemsResponses[keyof ItemsReadItemsResponses];

export type ItemsCreateItemData = {
    body: ItemCreate;
    path?: never;
    query?: never;
    url: '/api/v1/items/';
};

export type ItemsCreateItemErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ItemsCreateItemError = ItemsCreateItemErrors[keyof ItemsCreateItemErrors];

export type ItemsCreateItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type ItemsCreateItemResponse = ItemsCreateItemResponses[keyof ItemsCreateItemResponses];

export type ItemsDeleteItemData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type ItemsDeleteItemErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ItemsDeleteItemError = ItemsDeleteItemErrors[keyof ItemsDeleteItemErrors];

export type ItemsDeleteItemResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type ItemsDeleteItemResponse = ItemsDeleteItemResponses[keyof ItemsDeleteItemResponses];

export type ItemsReadItemData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type ItemsReadItemErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ItemsReadItemError = ItemsReadItemErrors[keyof ItemsReadItemErrors];

export type ItemsReadItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type ItemsReadItemResponse = ItemsReadItemResponses[keyof ItemsReadItemResponses];

export type ItemsUpdateItemData = {
    body: ItemUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type ItemsUpdateItemErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ItemsUpdateItemError = ItemsUpdateItemErrors[keyof ItemsUpdateItemErrors];

export type ItemsUpdateItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type ItemsUpdateItemResponse = ItemsUpdateItemResponses[keyof ItemsUpdateItemResponses];

export type TavilySearchData = {
    body: SearchRequest;
    path?: never;
    query?: never;
    url: '/api/v1/tavily/search';
};

export type TavilySearchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TavilySearchError = TavilySearchErrors[keyof TavilySearchErrors];

export type TavilySearchResponses = {
    /**
     * Successful Response
     */
    200: SearchResponse;
};

export type TavilySearchResponse = TavilySearchResponses[keyof TavilySearchResponses];

export type TavilyExtractData = {
    body: ExtractRequest;
    path?: never;
    query?: never;
    url: '/api/v1/tavily/extract';
};

export type TavilyExtractErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TavilyExtractError = TavilyExtractErrors[keyof TavilyExtractErrors];

export type TavilyExtractResponses = {
    /**
     * Successful Response
     */
    200: ExtractResponse;
};

export type TavilyExtractResponse = TavilyExtractResponses[keyof TavilyExtractResponses];

export type TavilyCrawlData = {
    body: CrawlRequest;
    path?: never;
    query?: never;
    url: '/api/v1/tavily/crawl';
};

export type TavilyCrawlErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TavilyCrawlError = TavilyCrawlErrors[keyof TavilyCrawlErrors];

export type TavilyCrawlResponses = {
    /**
     * Successful Response
     */
    200: CrawlResponse;
};

export type TavilyCrawlResponse = TavilyCrawlResponses[keyof TavilyCrawlResponses];

export type TavilyMapUrlsData = {
    body: MapRequest;
    path?: never;
    query?: never;
    url: '/api/v1/tavily/map';
};

export type TavilyMapUrlsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TavilyMapUrlsError = TavilyMapUrlsErrors[keyof TavilyMapUrlsErrors];

export type TavilyMapUrlsResponses = {
    /**
     * Successful Response
     */
    200: MapResponse;
};

export type TavilyMapUrlsResponse = TavilyMapUrlsResponses[keyof TavilyMapUrlsResponses];

export type PerplexityDeepResearchData = {
    body: PerplexityDeepResearchRequest;
    path?: never;
    query?: never;
    url: '/api/v1/perplexity/deep-research';
};

export type PerplexityDeepResearchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PerplexityDeepResearchError = PerplexityDeepResearchErrors[keyof PerplexityDeepResearchErrors];

export type PerplexityDeepResearchResponses = {
    /**
     * Successful Response
     */
    200: PerplexityDeepResearchResponse;
};

export type PerplexityDeepResearchResponse2 = PerplexityDeepResearchResponses[keyof PerplexityDeepResearchResponses];

export type GeminiDeepResearchSyncData = {
    body: GeminiDeepResearchRequest;
    path?: never;
    query?: never;
    url: '/api/v1/gemini/deep-research/sync';
};

export type GeminiDeepResearchSyncErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GeminiDeepResearchSyncError = GeminiDeepResearchSyncErrors[keyof GeminiDeepResearchSyncErrors];

export type GeminiDeepResearchSyncResponses = {
    /**
     * Successful Response
     */
    200: GeminiDeepResearchResultResponse;
};

export type GeminiDeepResearchSyncResponse = GeminiDeepResearchSyncResponses[keyof GeminiDeepResearchSyncResponses];

export type GeminiStartDeepResearchData = {
    body: GeminiDeepResearchRequest;
    path?: never;
    query?: never;
    url: '/api/v1/gemini/deep-research';
};

export type GeminiStartDeepResearchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GeminiStartDeepResearchError = GeminiStartDeepResearchErrors[keyof GeminiStartDeepResearchErrors];

export type GeminiStartDeepResearchResponses = {
    /**
     * Successful Response
     */
    200: GeminiDeepResearchJobResponse;
};

export type GeminiStartDeepResearchResponse = GeminiStartDeepResearchResponses[keyof GeminiStartDeepResearchResponses];

export type GeminiCancelDeepResearchData = {
    body?: never;
    path: {
        /**
         * Interaction Id
         */
        interaction_id: string;
    };
    query?: never;
    url: '/api/v1/gemini/deep-research/{interaction_id}';
};

export type GeminiCancelDeepResearchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GeminiCancelDeepResearchError = GeminiCancelDeepResearchErrors[keyof GeminiCancelDeepResearchErrors];

export type GeminiCancelDeepResearchResponses = {
    /**
     * Response Gemini-Cancel Deep Research
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type GeminiCancelDeepResearchResponse = GeminiCancelDeepResearchResponses[keyof GeminiCancelDeepResearchResponses];

export type GeminiPollDeepResearchData = {
    body?: never;
    path: {
        /**
         * Interaction Id
         */
        interaction_id: string;
    };
    query?: {
        /**
         * Last Event Id
         */
        last_event_id?: string | null;
    };
    url: '/api/v1/gemini/deep-research/{interaction_id}';
};

export type GeminiPollDeepResearchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GeminiPollDeepResearchError = GeminiPollDeepResearchErrors[keyof GeminiPollDeepResearchErrors];

export type GeminiPollDeepResearchResponses = {
    /**
     * Successful Response
     */
    200: GeminiDeepResearchResultResponse;
};

export type GeminiPollDeepResearchResponse = GeminiPollDeepResearchResponses[keyof GeminiPollDeepResearchResponses];

export type YoucomDeepResearchData = {
    body: YouComDeepResearchRequest;
    path?: never;
    query?: never;
    url: '/api/v1/youcom/deep-research';
};

export type YoucomDeepResearchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type YoucomDeepResearchError = YoucomDeepResearchErrors[keyof YoucomDeepResearchErrors];

export type YoucomDeepResearchResponses = {
    /**
     * Successful Response
     */
    200: YouComDeepResearchResponse;
};

export type YoucomDeepResearchResponse = YoucomDeepResearchResponses[keyof YoucomDeepResearchResponses];

export type PrivateCreateUserData = {
    body: PrivateUserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/private/users/';
};

export type PrivateCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PrivateCreateUserError = PrivateCreateUserErrors[keyof PrivateCreateUserErrors];

export type PrivateCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type PrivateCreateUserResponse = PrivateCreateUserResponses[keyof PrivateCreateUserResponses];
